### ISSUE TITLE
Minimap module hides "tracking" button.

### ISSUE THREAD

**Issue by gordoncaister** [bkader/KPack#1]
The tracking function is important to me, I use it to find mailboxes, repair sites, and many other useful things. I haven't been able to find an option to reenable the tracking function without disabling the entire minimap module, I really like the minimap module and would prefer an option to enable the tracker without disabling the minimap module.

**Comment by bkader** [comment]
Have tried Middle clicking on the minimal? Or right clickin?I forgot which one does what

**Comment by gordoncaister** [comment]
Ah! Middle-click does the trick. Somehow I didn't read that there was a middle click when I was reading the ReadMe. Great pack, thank you!
