### ISSUE TITLE
Conflicts with PQRotations

### ISSUE THREAD

**Issue by Andythem23** [bkader/KPack#5]

**Comment by Andythem23** [comment]
It says "has been blocked from an action available only to blizzard" when trying to do the rotation

**Comment by bkader** [comment]
Hello. Without the taint log or the error log this is a vague issue. It's advised to provide a more detailed description of the problem and some screenshots would be nice too. Also, make sure to try with KPack disabled.

**Comment by Andythem23** [comment]
taint log
    function AQNXPXXv_Debug(strText)
            if AQNXPXXv_DebugEnabled == true then
                AQNXPXXv_WriteToChat("[DEBUG] "..strText);
            end
        end

        function AQNXPXXv_SetDebug(enabled)
            if enabled == true then
                AQNXPXXv_DebugEnabled = true
            else
                AQNXPXXv_DebugEnabled = false
            end
        end

        function AQNXPXXv_WriteToChat(strText)
            if AQNXPXXv_ShowChat == true then
                print("|cffff7d0a<|r|cffffd200AQNXPXXv|r|cffff7d0a>|r "..strText)
            end
        end

        function AQNXPXXv_EventFrame_OnUpdate(self, elapsed)
	        AQNXPXXv_totalElapsed = AQNXPXXv_totalElapsed + elapsed;
	        AQNXPXXv_totalElapsed2 = AQNXPXXv_totalElapsed2 + elapsed;
            while (AQNXPXXv_totalElapsed2 > AQNXPXXv_UpdateInterval2) do
                AQNXPXXv_RegisterMovement(AQNXPXXv_totalElapsed2)
                AQNXPXXv_SetRecastDelay()

**Comment by Andythem23** [comment]
![imagen](https://user-images.githubusercontent.com/67170467/133877548-76591f10-c2b6-4e9f-bb9c-71eeed659c9c.png)

**Comment by Andythem23** [comment]
taint log
```
9/18 01:45:51.388  An action was blocked because of taint from KPack - UseItemByName()
9/18 01:45:51.388       function AQNXPXXvFunc0() if not functionsloaded then

		-- Party Check -- 
	partyCheck = function()
		if GetNumRaidMembers() > 0 
		or GetNumPartyMembers() > 0 then
			return true
		else
			return false
		end
	end

		-- Glyph Check -- 
	glyph = function(glyphID)
        local hasglyph = false;
        local i = 1;
        local glyph = GetGlyphSocketInfo(i);
        while glyph do
            local id = select(3, GetGlyphSocketInfo(i));
            if id == glyphID then
                hasglyph = true;
                break;
            end
            i = i + 1;
            glyph = GetGlyphSocketInfo(i);
        end
        return hasglyph;
    end
	
		-- Check target --
	function CanAttack()
	if UnitExists("target")
	and UnitCanAttack("player", "target") == 1
		then
			return true
		end
	end
		
		-- Check if player move --
	function pMove()
	if GetUnitSpeed("player") ~= 0
		then
			return true
		end
	end
	
		-- Check if player stay --
	function pStay()
	if GetUnitSpeed("player") == 0
		then
			return true
```

**Comment by bkader** [comment]
Well, there are 64 modules and I made sure that not a single one of them is causing taint nor using any protected function. The last one was `Unit Frames` and the problem was solved.
And the function **UseItemByName** doesn't not exist on ANY module on KPack, not in a single file. So the problem comes from elsewhere and KPack is the end victim.

**Comment by Andythem23** [comment]
That's weird because when I disable Kpack it works flawlessly. is a shame, such a good addon

**Comment by bkader** [comment]
Try to disable some of its module, starting of **BlizzBugsSuck**, **BlizzMove**, **Bubblicious**, **SnowfallKeyPress** and **SpeedyLoad** and see.
Just out of curiosity, can you show me the list of addons that are "ENABLED"?

**Comment by Andythem23** [comment]
Now I disabled every other addon and only left Kpack. The result is the same.

**Comment by Andythem23** [comment]
```
9/18 01:54:44.531  Execution tainted by KPack while reading MBHJqMZY_IsChanneling - 
        
        function MBHJqMZY_Debug(strText)
            if MBHJqMZY_DebugEnabled == true then
                MBHJqMZY_WriteToChat("[DEBUG] "..strText);
            end
        end

        function MBHJqMZY_SetDebug(enabled)
            if enabled == true then
                MBHJqMZY_DebugEnabled = true
            else
                MBHJqMZY_DebugEnabled = false
            end
        end

        function MBHJqMZY_WriteToChat(strText)
            if MBHJqMZY_ShowChat == true then
                print("|cffff7d0a<|r|cffffd200MBHJqMZY|r|cffff7d0a>|r "..strText)
            end
        end

        function MBHJqMZY_EventFrame_OnUpdate(self, elapsed)
	        MBHJqMZY_totalElapsed = MBHJqMZY_totalElapsed + elapsed;
	        MBHJqMZY_totalElapsed2 = MBHJqMZY_totalElapsed2 + elapsed;
            while (MBHJqMZY_totalElapsed2 > MBHJqMZY_UpdateInterval2) do
                MBHJqMZY_RegisterMovement(MBHJqMZY_totalElapsed2)
                MBHJqMZY_SetRecastDelay()
         
```

**Comment by Andythem23** [comment]
```
9/18 01:54:44.511  An action was blocked because of taint from KPack - CastSpellByID()
9/18 01:54:44.511      
        
        function MBHJqMZY_Debug(strText)
            if MBHJqMZY_DebugEnabled == true then
                MBHJqMZY_WriteToChat("[DEBUG] "..strText);
            end
        end

        function MBHJqMZY_SetDebug(enabled)
            if enabled == true then
                MBHJqMZY_DebugEnabled = true
            else
                MBHJqMZY_DebugEnabled = false
            end
        end

        function MBHJqMZY_WriteToChat(strText)
            if MBHJqMZY_ShowChat == true then
                print("|cffff7d0a<|r|cffffd200MBHJqMZY|r|cffff7d0a>|r "..strText)
            end
        end

        function MBHJqMZY_EventFrame_OnUpdate(self, elapsed)
	        MBHJqMZY_totalElapsed = MBHJqMZY_totalElapsed + elapsed;
	        MBHJqMZY_totalElapsed2 = MBHJqMZY_totalElapsed2 + elapsed;
            while (MBHJqMZY_totalElapsed2 > MBHJqMZY_UpdateInterval2) do
                MBHJqMZY_RegisterMovement(MBHJqMZY_totalElapsed2)
                MBHJqMZY_SetRecastDelay()
```

**Comment by Andythem23** [comment]
![imagen](https://user-images.githubusercontent.com/67170467/133877906-2c9e79f9-4c28-4f75-ba5a-30b2984260b5.png)
![imagen](https://user-images.githubusercontent.com/67170467/133877916-5b51c1ed-042c-476e-824b-da87a1c80b3a.png)
All were enabled. Now I just left Kpack

**Comment by bkader** [comment]
Can't you see there that the problem is **PQR**? KPack doesn't have a single module that's using a protected function whatsoever. `CastSpellByID` or `UseItemByName` are used by **PQR** and they are protected functions.
Try to disabled the module I mentioned about, try to disable **Unit Frames** with them and see.

**Comment by bkader** [comment]
> Taint errors can manifest in various ways, including "Interface action failed because of an AddOn" messages appearing in chat, and popups inviting players to disable specific addons. Most of the errors actually encountered by players are a result of unintended propagation of taint, rather than actual automation behavior being prevented (because most published addons are not trying to automate gameplay). Unfortunately, tracking the root cause of those issues is often not straightforward, as some errors require a specific sequence of events to occur before they trigger.
[Read More](https://www.townlong-yak.com/taint.log/about)

**Comment by Andythem23** [comment]
Thanks for the help. but even removing the modules you pointed, the problem persist. Now I understand that it doesn't have to do anything with Kpack

**Comment by Andythem23** [comment]
```
9/18 02:07:17.349  An action was blocked because of taint from KPack - CastSpellByID()
9/18 02:07:17.349      
        
        function MBHJqMZY_Debug(strText)
            if MBHJqMZY_DebugEnabled == true then
                MBHJqMZY_WriteToChat("[DEBUG] "..strText);
            end
        end

        function MBHJqMZY_SetDebug(enabled)
            if enabled == true then
                MBHJqMZY_DebugEnabled = true
            else
                MBHJqMZY_DebugEnabled = false
            end
        end

        function MBHJqMZY_WriteToChat(strText)
            if MBHJqMZY_ShowChat == true then
                print("|cffff7d0a<|r|cffffd200MBHJqMZY|r|cffff7d0a>|r "..strText)
            end
        end

        function MBHJqMZY_EventFrame_OnUpdate(self, elapsed)
	        MBHJqMZY_totalElapsed = MBHJqMZY_totalElapsed + elapsed;
	        MBHJqMZY_totalElapsed2 = MBHJqMZY_totalElapsed2 + elapsed;
            while (MBHJqMZY_totalElapsed2 > MBHJqMZY_UpdateInterval2) do
                MBHJqMZY_RegisterMovement(MBHJqMZY_totalElapsed2)
                MBHJqMZY_SetRecastDelay()
```

**Comment by bkader** [comment]
No problem. To fix your issue, get a patched EXE file with unlocked API functions **but with the risk of being banned because it sometimes can be detected** or simply get rid of PQR because after all it's a BOT.
