### ISSUE TITLE
Incoming Cast shown on Target Castbar(Nameplates)

### ISSUE THREAD

**Issue by Kahuma1** [bkader/KPack#6]
When in raid and a mob beginns a cast it shows the name of that cast correctly. When sombody else beginns casting a spell on said mob it shows the incoming cast and switches between them if more then 1 person is casting on the same mob.
Should be the same Issue as in KuiNameplates (Only update castbar spell if for the matched unit ).
Reported this already but this is just to remind you since you said that u forget the stuff on DC.

**Comment by Kahuma1** [comment]
No you did revert it back to the original version.
I am sorry i shouldn´t have put it as an issue.

**Comment by bkader** [comment]
I am afraid I no longer have the time nor the energy to add this feature, closing this issue.
My apologies.
